ARG PYRENEW_VERSION=v0.1.1

FROM python:3.12

RUN apt-get update
RUN apt-get install -y r-base
RUN apt-get install -y cmake
RUN pip install --root-user-action=ignore -U pip
RUN pip install --root-user-action=ignore git+https://github.com/cdcgov/pyrenew.git@${PYRENEW_VERSION}

CMD ["bash"]
