FROM python:3.13

RUN apt-get update
RUN apt-get install -y r-base
RUN apt-get install -y cmake
RUN pip install --root-user-action=ignore -U pip
RUN pip install --root-user-action=ignore \
    git+https://github.com/cdcgov/pyrenew.git@v0.1.1

CMD ["bash"]
