name: "Set up hewr"
description: "This action sets up R with the hewr package installed."
inputs: {}
runs:
  using: "composite"
  steps:
    - uses: action/checkout@v4

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: "release"
        use-public-rspm: true

    - name: "Set up dependencies for hewr"
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        working-directory: hewr

    - name: Install hewr
      run: pak::local_install("hewr", ask = FALSE)
      shell: Rscript {0}
