name: Delete branch tag from container registry

on:
  delete:
  workflow_dispatch:
    inputs:
      tag:
        description: The name of the tag to delete. Usually the branch name.
        type: string

env:
  IMAGE_NAME: pyrenew-hew

jobs:
  delete-container:
    permissions:
      contents: read
      packages: write
    environment: production
    runs-on: ubuntu-latest
    name: Delete tag

    steps:
      - name : Checkout code
        uses: actions/checkout@v5

      - name: Figure out tag (either latest if it is main or the branch name)
        id: image-tag
        run: |
          if [ "${{ inputs.tag }}" = "latest" ]; then
            echo "The image associated with the main branch cannot be deleted."
            exit 1
          else
            echo "tag=${{ github.event.ref }}" >> $GITHUB_OUTPUT
          fi

      # Deleting a package from GHCR by tag name is surprising complex
      # This action has been approved for use on cdcent/cdcgov by the CDC Github Team
      # https://github.com/snok/container-retention-policy
      - name: Delete image tag
        uses: snok/container-retention-policy@v3.0.1
        with:
          account: ${{ github.repository_owner }}
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: ${{ env.IMAGE_NAME }}
          image-tags: ${{ inputs.tag || steps.image-tag.outputs.tag }}
          cut-off: 1s # required, minimum package age to be a candidate for deletion
