name: Delete branch tag from container registry

on:
  delete:

env:
  IMAGE_NAME: pyrenew-hew

jobs:
  delete-container:
    permissions:
      contents: read
      id-token: write
      packages: read
    environment: production
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    name: Delete tag

    steps:
      - name : Checkout code
        uses: actions/checkout@v4

      - name: Figure out tag (either latest if it is main or the branch name)
        id: image-tag
        run: |
          if [ "${{ github.event.ref }}" = "main" ]; then
            echo "The image associated with the main branch cannot be deleted."
            exit 1
          else
            echo "tag=${{ github.event.ref }}" >> $GITHUB_OUTPUT
          fi

      # From: https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#requesting-the-jwt-using-the-actions-core-toolkit
      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client
      - name: Get Id Token
        uses: actions/github-script@v7
        id: idtoken
        with:
          script: |
            const coredemo = require('@actions/core')
            const id_token = await coredemo.getIDToken('api://AzureADTokenExchange')
            coredemo.setOutput('id_token', id_token)

      - name: ACR Import
        uses: CDCgov/cfa-actions/runner-action@v1.3.0
        with:
          github_app_id: ${{ secrets.REPO_CDCENT_ACTOR_APP_ID }}
          github_app_pem: ${{ secrets.REPO_CDCENT_ACTOR_APP_PEM }}
          wait_for_completion: true
          print_logs: true
          script: |
            echo "Logging into Azure CLI"
            az login --service-principal \
            --username ${{ fromJSON(secrets.EDAV_STF_SERVICE_PRINCIPAL).clientId }} \
            --tenant ${{ fromJSON(secrets.EDAV_STF_SERVICE_PRINCIPAL).tenantId }} \
            --federated-token ${{ steps.idtoken.outputs.id_token }} \
            --output none

            echo "Remove the image from the registry"
            az acr repository delete \
              --yes \
              --name ${{ vars.CONTAINER_REGISTRY_NAME }} \
              --image ${{ env.IMAGE_NAME }}:${{ steps.image-tag.outputs.tag }} && echo "Deleted image tag!"

            if [ $? -ne 0 ]; then
              echo "Failed to delete image tag"
            fi
