name: Delete branch tag from container registry

on:
  delete:

env:
  IMAGE_NAME: pyrenew-hew

jobs:
  delete-container:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    name: Delete tag

    steps:
      - name : Checkout code
        uses: actions/checkout@v4

      - name: Figure out tag (either latest if it is main or the branch name)
        id: image-tag
        run: |
          if [ "${{ github.event.ref }}" = "main" ]; then
            echo "The image associated with the main branch cannot be deleted."
            exit 1
          else
            echo "tag=${{ github.event.ref }}" >> $GITHUB_OUTPUT
          fi

      - name: ACR Import
        uses: CDCgov/cfa-actions/runner-action@v1.3.0
        with:
          github_app_id: ${{ secrets.REPO_CDCENT_ACTOR_APP_ID }}
          github_app_pem: ${{ secrets.REPO_CDCENT_ACTOR_APP_PEM }}
          wait_for_completion: true
          print_logs: true
          script: |
            az login --service-principal \
            --username ${{ fromJSON(secrets.EDAV_STF_SERVICE_PRINCIPAL).clientId }} \
            --password ${{ fromJSON(secrets.EDAV_STF_SERVICE_PRINCIPAL).clientSecret }} \
            --tenant ${{ fromJSON(secrets.EDAV_STF_SERVICE_PRINCIPAL).tenantId }}

            # Remove the image from the registry
            az acr repository delete \
              --yes \
              --name ${{ vars.CONTAINER_REGISTRY_NAME }} \
              --image ${{ env.IMAGE_NAME }}:${{ steps.image-tag.outputs.tag }}

            # Remove the dependencies image from the registry
            az acr repository delete \
              --yes \
              --name ${{ vars.CONTAINER_REGISTRY_NAME }} \
              --image ${{ env.IMAGE_NAME }}:dependencies-${{ steps.image-tag.outputs.tag }}
