name: My Sample Environment Detection Workflow
on:
    workflow_dispatch:

jobs:

  set-environment:
    runs-on: ubuntu-latest
    outputs:
      ENVIRONMENT_NAME: ${{ steps.set-env-step.outputs.ENVIRONMENT_NAME }}
    steps:
      - id: set-env-step
        run: |
          # or whatever logic you want to determine environment,
          # you could do 'ENVIRONMENT_NAME=${GITHUB_REF_NAME} >> $GITHUB_OUTPUT' for simplicity
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "ENVIRONMENT_NAME=production" >> $GITHUB_OUTPUT
          else
            echo "ENVIRONMENT_NAME=test" >> $GITHUB_OUTPUT
          fi

  detect-environment:
    needs: set-environment
    environment: ${{ needs.set-environment.outputs.ENVIRONMENT_NAME }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to ${{ needs.set-environment.outputs.ENVIRONMENT_NAME }}"

      - if: ${{ needs.set-environment.outputs.ENVIRONMENT_NAME == 'production' }}
        run: echo "This is a production deployment"

      - if: ${{ needs.set-environment.outputs.ENVIRONMENT_NAME == 'test' }}
        run: echo "This is a test deployment"
